[project]
name = "stats-reader"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "cattrs>=25.1.1",
]

[project.scripts]
print-objects = "mp_reader.__main__:main"
